using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace IlinkDb.Data.MemoryDb
{
    public class RandomData
    {
        // private readonly Random _random = new Random((int)DateTime.Now.Ticks & 0x0000FFFF);
        private Random _random = new Random((int)DateTime.Now.Ticks & 0x0000FFFF);

        #region Initialize String Data

        private readonly string[] _words = new[]
        {
            "lorem", "ipsum", "dolor", "sit", "amet", "nonumy", "eirmod", "tempor",
            "invidunt", "ut", "labore", "et", "dolore", "magna", "aliquyam", "erat", "sed",
            "diam", "voluptua", "at", "vero", "eos", "et", "accusam", "et", "justo", "duo",
            "dolores", "et", "ea", "rebum", "stet", "clita", "kasd", "gubergren", "no", "sea"
            , "takimata", "sanctus", "est", "lorem", "ipsum", "dolor", "sit", "amet", "lorem"
            , "ipsum", "dolor", "sit", "amet", "consetetur", "sadipscing", "elitr", "sed",
            "diam", "nonumy", "eirmod", "tempor", "invidunt", "ut", "labore", "et", "dolore",
            "magna", "aliquyam", "erat", "sed", "diam", "voluptua", "at", "vero", "eos", "et"
            , "accusam", "et", "justo", "duo", "dolores", "et", "ea", "rebum", "stet",
            "clita", "kasd", "gubergren", "no", "sea", "takimata", "sanctus", "est", "lorem",
            "ipsum", "dolor", "sit", "amet", "lorem", "ipsum", "dolor", "sit", "amet",
            "consetetur", "sadipscing", "elitr", "sed", "diam", "nonumy", "eirmod", "tempor",
            "invidunt", "ut", "labore", "et", "dolore", "magna", "aliquyam", "erat", "sed",
            "diam", "voluptua", "at", "vero", "eos", "et", "accusam", "et", "justo", "duo",
            "dolores", "et", "ea", "rebum", "stet", "clita", "kasd", "gubergren", "no", "sea"
            , "takimata", "sanctus", "est", "lorem", "ipsum", "dolor", "sit", "amet", "duis",
            "autem", "vel", "eum", "iriure", "dolor", "in", "hendrerit", "in", "vulputate",
            "velit", "esse", "molestie", "consequat", "vel", "illum", "dolore", "eu",
            "feugiat", "nulla", "facilisis", "at", "vero", "eros", "et", "accumsan", "et",
            "iusto", "odio", "dignissim", "qui", "blandit", "praesent", "luptatum", "zzril",
            "delenit", "augue", "duis", "dolore", "te", "feugait", "nulla", "facilisi",
            "lorem", "ipsum", "dolor", "sit", "amet", "consectetuer", "adipiscing", "elit",
            "sed", "diam", "nonummy", "nibh", "euismod", "tincidunt", "ut", "laoreet",
            "dolore", "magna", "aliquam", "erat", "volutpat", "ut", "wisi", "enim", "ad",
            "minim", "veniam", "quis", "nostrud", "exerci", "tation", "ullamcorper",
            "suscipit", "lobortis", "nisl", "ut", "aliquip", "ex", "ea", "commodo",
            "consequat", "duis", "autem", "vel", "eum", "iriure", "dolor", "in", "hendrerit",
            "in", "vulputate", "velit", "esse", "molestie", "consequat", "vel", "illum",
            "dolore", "eu", "feugiat", "nulla", "facilisis", "at", "vero", "eros", "et",
            "accumsan", "et", "iusto", "odio", "dignissim", "qui", "blandit", "praesent",
            "luptatum", "zzril", "delenit", "augue", "duis", "dolore", "te", "feugait",
            "nulla", "facilisi", "nam", "liber", "tempor", "cum", "soluta", "nobis",
            "eleifend", "option", "congue", "nihil", "imperdiet", "doming", "id", "quod",
            "mazim", "placerat", "facer", "possim", "assum", "lorem", "ipsum", "dolor", "sit"
            , "amet", "consectetuer", "adipiscing", "elit", "sed", "diam", "nonummy", "nibh",
            "euismod", "tincidunt", "ut", "laoreet", "dolore", "magna", "aliquam", "erat",
            "volutpat", "ut", "wisi", "enim", "ad", "minim", "veniam", "quis", "nostrud",
            "exerci", "tation", "ullamcorper", "suscipit", "lobortis", "nisl", "ut",
            "aliquip", "ex", "ea", "commodo", "consequat", "duis", "autem", "vel", "eum",
            "iriure", "dolor", "in", "hendrerit", "in", "vulputate", "velit", "esse",
            "molestie", "consequat", "vel", "illum", "dolore", "eu", "feugiat", "nulla",
            "facilisis", "at", "vero", "eos", "et", "accusam", "et", "justo", "duo",
            "dolores", "et", "ea", "rebum", "stet", "clita", "kasd", "gubergren", "no", "sea"
            , "takimata", "sanctus", "est", "lorem", "ipsum", "dolor", "sit", "amet", "lorem"
            , "ipsum", "dolor", "sit", "amet", "consetetur", "sadipscing", "elitr", "sed",
            "diam", "nonumy", "eirmod", "tempor", "invidunt", "ut", "labore", "et", "dolore",
            "magna", "aliquyam", "erat", "sed", "diam", "voluptua", "at", "vero", "eos", "et"
            , "accusam", "et", "justo", "duo", "dolores", "et", "ea", "rebum", "stet",
            "clita", "kasd", "gubergren", "no", "sea", "takimata", "sanctus", "est", "lorem",
            "ipsum", "dolor", "sit", "amet", "lorem", "ipsum", "dolor", "sit", "amet",
            "consetetur", "sadipscing", "elitr", "at", "accusam", "aliquyam", "diam", "diam",
            "dolore", "dolores", "duo", "eirmod", "eos", "erat", "et", "nonumy", "sed",
            "tempor", "et", "et", "invidunt", "justo", "labore", "stet", "clita", "ea", "et",
            "gubergren", "kasd", "magna", "no", "rebum", "sanctus", "sea", "sed", "takimata",
            "ut", "vero", "voluptua", "est", "lorem", "ipsum", "dolor", "sit", "amet",
            "consetetur", "sadipscing", "elitr", "sed", "diam", "consetetur", "sadipscing", "elitr",
            "sed", "diam", "nonumy", "eirmod", "tempor", "invidunt", "ut", "labore", "et",
            "dolore", "magna", "aliquyam", "erat", "consetetur", "sadipscing", "elitr", "sed",
            "diam", "nonumy", "eirmod", "tempor", "invidunt", "ut", "labore", "et",
            "dolore", "magna", "aliquyam", "erat", "sed", "diam", "voluptua", "at", "vero",
            "eos", "et", "accusam", "et", "justo", "duo", "dolores", "et", "ea", "rebum",
            "stet", "clita", "kasd", "gubergren", "no", "sea", "takimata", "sanctus", "est",
            "lorem", "ipsum"
        };

        private readonly string[] _names = new[]
        {
            "Tina Crumpet (British Hospitality Advisor)",
            "Begonia Payne-Diaz (Customer Service Specialist)",
            "Zbigniew Kuptz (Director of Cosmetic Surgery)",
            "Lucy Lastic (Plumber's Crack Apologist)",
            "Moses Lonergan (Obsessive Yard Care Specialist)",
            "Luke A. Boyd (Ornithology Intern)",
            "Rose Dior (Sculling Coach)",
            "Kay Keneetit (Work and Leisure Time Coach)",
            "Douse and Burnham (401K Statement Analysts)",
            "Imelda Czechs (Accounts Payable Administrator)",
            "Sue Flockey (Aegean Caterer)",
            "Dasha Chekhov (Accounts Payable Clerk, Moscow Office)",
            "Vishnu Payup (Accounts Receivable Supervisor from the Mumbai Office)",
            "Bjorn A. Payne Diaz (Adopted Son from Sweden)",
            "Wilma Butfit (Airline Seat Tester)",
            "Carmine Dioxide (Air-Quality Monitor)",
            "Ulanda U. Lucky (Air Traffic Controller)",
            "Will Price Randomly (Airline Reservation Manager)",
            "Rush Inuit (Alaskan Prenuptial Advisor)",
            "Lou Segusi (Alignment Inspector)",
            "Amanda Livering Cole (Alternative Fuel Consultant)",
            "Kirsten Hollered (Anger Management Coach)",
            "Joanne Slowburner (Anger Management Consultant)",
            "Turner Luce (Animal Control Officer)",
            "Everett Possum (Appalachian Chef)",
            "Bud Uronner (Appeals Specialist)",
            "Barbara Ganush (Appetizer Coordinator)",
            "Stu Earley (Appointment Secretary)",
            "Amadeus O. Early (Appointment Secretary II)",
            "Viola Fuss (Arbitration Expert)",
            "Phyllis Steen (Art Critic)",
            "Dot Snice (Art Critic II)",
            "Luciano Pavearoadi (Asphalt Contractor)",
            "Lois Steem (Assertiveness Training Coach)",
            "Kurt Reply (Assistant Customer Care Representative)",
            "Sy Burnett and Sy Quest (Asst. Directors of Computer Services)",
            "Hugo Gurll (Assistant Director of Moral Support)",
            "Gladys Radio (Assistant to our Make Up Artist)",
            "Kent C. Detrees (Assistant Director of Strategic Planning)",
            "Joaquin D'Planque (Assistant Disciplinarian)",
            "Lisa Carr (Asst. Fleet Manager)",
            "Lotta B. Essen (Assistant to the PR Specialist)",
            "Orson Buggy (Asst. Transportation Coordinator)",
            "Nomar Wheaton (Astroturf Installer)",
            "Janet Torino (Attorney General)",
            "Hubert H. Humvee II (Attorney General in charge of Tobacco Settlements)",
            "Hugh Wake (Audience Counter)",
            "Adam Illion (Audience Estimator)",
            "Luke Warm (Audience Response Analyst)",
            "Joaquin Matilda (Australian Tour Guide)",
            "James Bondo (Auto-Body Expert)",
            "Rusty Steele (Automotive Finishes Consultant)",
            "Dr. Denton Fender (Automotive Medical Researcher)",
            "Megan Model (Automotive Registrar)",
            "Fitz Matush (Auto Seat Tester)",
            "Veronica Lizzioncourse (Back Seat Driver)",
            "Mischa Turnov (Back Seat Driver II)",
            "Nadia Geddit (Bad Joke Interpreter)",
            "Freida Gogh (Bail Bond Provider)",
            "Frieda Wander (Bail-Bondswoman)",
            "Sasha Noyes (Band Leader)",
            "Nikolai Putin (Banker, Car Talk Plaza Poker Games)",
            "Lotta Bullnose (Bathroom Tile Installer)",
            "Ed Amame (Bean Counter)",
            "Juan Zapata (Bedtime Storyteller)",
            "Wyatt B. Hoovesia (Behavior Consultant)",
            "Vera Lee Isay (Biblical Scholar)",
            "Juan Anatou (Big Band Leader)",
            "Mahamadan Ptolemy (Blues Coordinator)",
            "I. Shelby Released (Bob Dylan Specialist)",
            "Tilda Plierslip (Bolt Tightener)",
            "Odessa Paige Turner (Book Critic)",
            "Hadley Newham (Boston Funeral Director)",
            "Menachem Down (Bowling Coach)",
            "Schlomo Quigley (Brake Adjuster)",
            "Eureka Garlic (Breathalyzer Administrator)",
            "Sir Irving Spoon (British Cutlery Specialist)",
            "Isaiah Olchap (British Doorman)",
            "Ike and Stan Musicals (Broadway Reviewer)",
            "Major Payne-Diaz (Brother in the Military)",
            "Laura Biden (Boston Traffic Director)",
            "Sasha Titus (Budget Director)",
            "Hugo First (Bunji Jumping Instructor)",
            "Angus MacCoatup (Butler in Car Talk's Scotland Division)",
            "Phillip Airtime (Broadcast Philosopher)",
            "Luigi Bord (Business Forecaster)",
            "L. Ron Cupboard (Cabinet Maker)",
            "Bruno Moore (Caffeine Addiction Counselor)",
            "Carlos Antenna (Car Stereo Installer)",
            "Euripedes Ibreakayourface (Car Talk Bouncer)",
            "Sam Boney (Car Talk Ice Rink Manager)",
            "Barbara Seville (Car Talk Opera Critic)",
            "Richard Gere-Oil, Mick Jaguar (Celebrity Consultants)",
            "Alan Greasepan (Chairman, Federal Lubrication Board)",
            "John Shall-I-Pop-a-Wheelie (Chairman, Joint Chiefs of Staff)",
            "Horatio Algebra (Chairman, Math Dept.)",
            "Amos Reid (Chairman of our Southern Literature Department)",
            "Ira Caull (Chairman, Oral History Dept.)",
            "Victor Analysis (Chairman, Staff Physics Dept.)",
            "Art Majors (Chairman, Underemployment Study Group)",
            "Kent Hoyt (Chicken Soup Provisioner)",
            "Candace B. Rittenoff (Chief Accountant)",
            "Myra Chunkle (Chief Benefactor)",
            "Chef Boyar Ubusy (Chief Cook and Bottle Washer)",
            "Edward James Almost (Chief Estimator)",
            "Otto Delupe (Chief Information Officer)",
            "Harry Mental, aka Judge Mental (Chief Justice)",
            "Hugh Louis Dewey of Dewey, Cheetham & Howe (Chief Legal Counsel)",
            "Bernadette Bridge (Chief Negotiator)",
            "Wayne Back (Chief of Stadium Seating for the Olympics)",
            "Juan Menudo (Chief Procrastinator)",
            "Jacques Hughes (Chief Procrastinator, Paris Office)",
            "Emma Chizzit (Chief Procurement Officer)",
            "Yessir Itsaflat (Chief of Tire Technology)",
            "A. Hugh Nokitov (Child Care Provider)",
            "Dr. Benjamin Spark (Child Development Expert)",
            "Minnie Van Driver (Child Transportation Specialist)",
            "Bea Ferrone (Children's Menu Adviser)",
            "Al Lowetta (Children's Music Programmer)",
            "Amos Muhmahmi (Children's Sleepover Coordinator)",
            "Anna Paulina Roma (Cigar Smoke Monitor)",
            "Julie Verley (Class Attendance Monitor)",
            "Sidney Furst Rowe (Class Valedictorian)",
            "Adolph Deflor (Cleanliness Inspector)",
            "Saul Wellingood (Cliché Monitor)",
            "Jillian Here (Climate Change Monitor)",
            "Colette O'Day (Clock Watcher)",
            "Hugh Jass (Clothing Designer)",
            "Ben Thayer, Don Thatt (Co-Chairmen of Apathy Study Group)",
            "Carmella Highwater (Coffee Break Manager)",
            "Colin Duboise (Collections Specialist)",
            "Jesse 'The Body Shop' Ventura (Collision Repair Specialist)",
            "Gladys Overwith (Commencement Speaker)",
            "George Stayontopothis (Communications Director)",
            "Noam Sayin (Communications Director II)",
            "Kay C. Deech (Communications Specialist, Rome Office)",
            "Ophelia Paine (Compassion Coordinator)",
            "Xavier Breath (Complaint Line Operator)",
            "Levon Hold (Complaint Line Operator II)",
            "Billy Aiken (Complaint Resolution Specialist)",
            "C. Colin Backslash (Computer Hardware Specialist)",
            "C. Boynton Glick (Computer Instructor)",
            "Sludgy Ozawa (Conductor Emeritus, Tappet Brothers Symphony Orchestra)",
            "Philip Harmonic (Conductor, Tappet Brothers Symphony Orchestra)",
            "Hugo Origo (Conflict Resolution Specialist)",
            "Yvonne Apeesamey (Conflict Resolution Specialist)",
            "Orrin Hatchback, Dan Rustencarski, Paul Simonize, B. F. Gingrich (Congressional Lobbyists)",
            "Eileen Tudor-Wright (Conservative Political Commentator)",
            "Nadia Belimi (Conspiracy Theorist)",
            "Dustin Dubree (Construction Manager)",
            "Evan Elpus (Contract Extension Negotiator)",
            "Cody Pendant (Coordinator, 12-Step Recovery Program)",
            "Don Juan-Gogh (Coordinator of Summer Visits to the Inlaws)",
            "Pat Pending (Copyright Attorney)",
            "Hugh Lyon Sack (Corporate Spokesperson)",
            "Hope Anna Prayer (Crash Tester)",
            "Drew A. Blank (Creative Director)",
            "Max Stout (Credit Counselor)",
            "Lauren Order (Criminal Justice Expert)",
            "Eton Doolittle (Cruise Activity Planner)",
            "Isiah Lilprair (Curator of Dionne Warwick Studies)",
            "Brittany Spears (Curator of our French Armaments Exhibit)",
            "Rex Galore (Curator of Tom's Car Collection)",
            "Haywood Jabuzoff (Customer Car Care Representative)",
            "Dot Stubadd (Customer Car Care Representative Assistant)",
            "Noah Wayne Hellman (Customer Credit Officer)",
            "Mel Pugh (Customer Greeter)",
            "Amelia Loos (Day Old Seafood Chef)",
            "Konrad Adenauer (Daylight Savings Time Manager)",
            "Sir Leo Mann (Customer Service Representative from London Office)",
            "Justin Volk V (Defense Attorney)",
            "Heronimus B. Blind (Defense Attorney II)",
            "Donnatella Dicoppas (Defense Attorney III)",
            "Gil T. Azell (Defense Attorney IV)",
            "Major Error (Defense Dept. Consultant)",
            "Ginger Vitis (Dental Hygienist)",
            "Don Pickett (Dermatologist for Teenagers)",
            "Ike Arumba (Desi Arnaz Biographer)",
            "Tyra Meesu (Dessert Chef)",
            "Eaton Flanagan (Dessert Menu Planner)",
            "Bill Shredder (Director of Accounts Payable)",
            "Theresa Pollinating (Director of Allergy Research)",
            "O. Leo Lahey (Director of Alpine Choir)",
            "Boris Karlarm (Director of Automotive Security)",
            "Ricardo Dismantleban (Director, Automotive Recycling Center (aka Junkyard))",
            "Toulouse Toutrack (Director of Cadillac Steering)",
            "La Toyota Jackson (Director of The Car Talk Psychic Network)",
            "Noh Tie, Woo! (Designer of Casual Clothing Line)",
            "Russell Upsumgrub (Director of Catering)",
            "Ron DesVue (Director of Clandestine Meetings)",
            "Martina Neverturnover (Director of Cold Weather Starting)",
            "Gus O'Genn (Director of Computer Diagnostics)",
            "Dot Matrix (Director of Computer Services)",
            "Fred Knott (Director of Congressional Funding)",
            "Stan Beyerman (Director of Country Music)",
            "Marianna Trench (Director of Deep Sea Research)",
            "Anita Hammer (Director of Delicate Electronics Repair)",
            "Sandy Berger (Director of Desert Food Supplies)",
            "Al Takaka (Director of Elder Affairs)",
            "Peggy Flaming (Director of E-mail Responses)",
            "Upton Leftus (Director of Employee Loyalty Program)",
            "U. Lyon Sack (Director of Ethics & Honesty)",
            "Ivana Michelin (Director of Firestone Tire Recalls)",
            "Amanda B. Reckondwyth (Director of Gender Studies)",
            "Nomar Winter (Director of Global Warming)",
            "Iona Heap (Director of Grad Student Transportation)",
            "Lucinda Boltz (Director of Guaranteed Repeat Business)",
            "Ricardo Montana-Bahn (Director of High-Speed Impact Studies)",
            "Noah U. Turna (Director of Italian Traffic Enforcement)",
            "Picabo Street (Director of Intensive Care Unit (The Picabo ICU))",
            "Reggae Jackson (Director of Jamaican Baseball Operations)",
            "Emperor Overhito (Director of Japanese Cooling Systems)",
            "Chico Maniorda (Director of Latin American Shameless Commerce)",
            "Noah Fundrive (Director of Listener Support)",
            "Olive Presser (Director of Lubrication)",
            "Toney Blare (Director of Luxury Car Horns)",
            "Kay Sera (Director of Long-Range Strategic Planning)",
            "Juan Moorehouse (Director of Monopoly Policy)",
            "Warren T. Mifutt (Director of New Product Repair)",
            "Rose Hips (Director of Nutritional Supplements)",
            "Isabelle Ringing (Director of Pavlovian Research)",
            "Carless Castenada (Director of Pedestrian Operations)",
            "Len Scapon (Director of Photography)",
            "A. Kurt Nod (Director of Positive Reinforcement)",
            "Maury Missions (Director of Pollution Control)",
            "Oscar Ruitt (Director of Preventive Maintenance)",
            "Lois Bidder (Director of Purchasing)",
            "Donatella Debois (Director of Puzzler Answer Luxury Gift Reception)",
            "Les Thomas and Nomar Raymond (Directors of Quality Control)",
            "Eamon Lowe (Director of Quality Control II)",
            "Nomar Car-seat-repairer (Director of Red Sox Themed Upholstery)",
            "Sylvia Pottholi (Director of Roadway Resurfacing)",
            "Yevgeny Primercoat (Director of Russian Rust Protection)",
            "Slow-Me-Down Milosevic (Director of Speed Bumps)",
            "Linus Scrimmage (Director of Sports Information)",
            "Holly Unlikely (Director of Staff Bonuses)",
            "Ray Vaughn (Director of Staff Bonuses II)",
            "Xavier Breath (assisted by Tony Von Thinkett!) (Director of Staff Pay Increases)",
            "Red Auerbach (Director of Standard Time)",
            "Eileen Yorway (Director of Sycophantic Activities)",
            "Lee Eyeapoka (Director of Three Stooges Studies)",
            "Donatello Nobatti (Director of Top Secret Strategy)",
            "H. Ross Peugeot (Director of Unsolicited Advice)",
            "Zbigniew Chrysler (Director of Upward Mobility in Eastern Europe)",
            "Ewell Rudy Day (Director of Vengeance)",
            "Sumner Reruns (Director of Warm-Weather Programming)",
            "Holly Unlikely (Director of Year-End Bonuses)",
            "Don Fuller Round (Disciplinarian)",
            "Ophelia Self (Disgruntled Massage Therapist)",
            "Jaime Royal Payne Diaz (Distant Cousin in Mexico City)",
            "Carmine Nottyors (Divorce Attorney)",
            "Euripedes Upmann (Document Security Expert from Jamaica)",
            "Don Chase Katz (Dog Trainer)",
            "Annie Von Holm (Door-to-Door Sales)",
            "Thad Hertz (Dope Slap Administrator)",
            "Noah Vale (Dougie's Live-in Fashion Improvement Coach)",
            "Candace Guy (Downsizing Consultant)",
            "Placebo Domingo (Drug Trials Specialist)",
            "Preston Creases (Drycleaner)",
            "Roland Rock (Dyslexic Rock and Roll Music Critic)",
            "Constance R. Rowe (Early American Folk Music Specialist)",
            "Alexander Soldyernissan (East Asian Used Car Expert)",
            "Selma Junkoff (Ebay Specialist)",
            "Sammy Conductor (Electronics Technician)",
            "Richard Shun (aka Dick) (Elocution Coach)",
            "Amal Shookup (Elvis Impersonator)",
            "Joe Klein (Emergency Humor Hotline Operator)",
            "Ron Lykell (Emergency Preparedness Director)",
            "Henrietta Badclam (Emergency Room Physician)",
            "Justin Hale VII (I, II,III, IV, V, VI may they RIP) (Emissions Tester)",
            "Enzo Watt (Empathy Coach)",
            "Phil Lacrap and his brother Luke Lacrap (Employee Morale Boosters)",
            "Trudy Gauntlet (Employee Orientation Specialist)",
            "Carmen Dating (Employee Refrigerator Monitor)",
            "Laura Deboom (Employee Terminator)",
            "Jean Claude Air Damme (Engine Cooling Systems Manager)",
            "Vera Bruptly (Evasive Driving Instructor)",
            "Russell Papus (Executive Coach)",
            "Eustace Stahl (Executive Washroom Attendant)",
            "Liza Round (Exercise Guru)",
            "Manny Burns (Exhaust Manifold Specialist)",
            "Joaquin Joaquout (Express Oil Change Provider)",
            "Ella Fynoe (Fact Checker)",
            "C.S. Verdad (Fact Checker, Mexico City Office)",
            "Natalie Attired (Fashion Consultant)",
            "Noah Vale (Fashion Improvement Coach)",
            "Royal Payne Diaz (Father-in-Law Liaison)",
            "Rhea Rangit (Feng Shui Consultant in Mumbai)",
            "Landon McKeaster (Figure Skating Coach)",
            "Illgott and Gaines (Financial Advisors)",
            "Lou Gubrious (Financial Forecaster)",
            "Renata Oil (Fleet Maintenance Manager)",
            "Oscar de la Rental (Fleet Manager)",
            "Howard M. Burgers (Food Taster)",
            "Susan Shocks (Footwear Consultant)",
            "Hugh Don Wannano (401 K Advisor)",
            "Maurice Chevrolet (French Automotive Liaison)",
            "Gerard Diaperdoo (French Child Care Coordinator)",
            "Poupon Degrasse (French Dogwalker)",
            "John T. Alouetta (French Folk Music Historian)",
            "Henri Rependent (French Ford Expedition Driver)",
            "April Lynn Parris (French Vacation Specialist)",
            "Althea Andrasia (Gambling Addiction Counselor)",
            "Stan Beck (Gas Tank Welder)",
            "Cameron Diaz (Gastroenterologist)",
            "Donna Maria Eucuzzin (Genetic Counselor in Rome)",
            "Axel Hausen (German Interpreter)",
            "Litre Vino (Golf and Wine Correspondent)",
            "Putnam Daily (Golf Pro)",
            "Colin Response (Gospel Choir Director)",
            "Val and Dick Torian (Graduation Coordinators)",
            "I.M. Shirley Wright (Grammar Consultant)",
            "Adjustes Miros (Greek Driving Instructor)",
            "Costa Grand (Greek Insurance Estimator)",
            "The Horseshoe Road Inn (Guest Accommodations)",
            "Les Block (Guide to Rapid Sun Tanning)",
            "Perry O'Dontal (Gum Surgeon)",
            "I.M. Mr. Gigi (Hair)",
            "Dewey R. Donti (Hair Color Consultant)",
            "Hedda Harrigan (Hair Restoration Specialist)",
            "Toulouse Toulong (Head of Alterations)",
            "Moe D'Lawn (Head of Bldgs. & Grounds)",
            "Dinah Tell (Head of Covert Operations)",
            "Dawn Boddame (Head of Customer Service)",
            "Ewen Whadarmy (Head of Division of Threat Assessment)",
            "Constance Noring (Head of Front Desk Security)",
            "C. Howie Run (Head of Personal Security)",
            "Barb Dwyer (Head of Security)",
            "Olivia McColon (Head of our Organ Donation Program)",
            "Al Lloyd Wheel, Constance Velocity (Heads of Parts Dept.)",
            "Ewell B. Hoffinett (Head of Used Car Purchasing)",
            "Selma Kayak (Head of Watersports Marketing)",
            "Erasmus B. Dragon (Head of Working Mother Support Group)",
            "Dan Difino (Help Desk Coordinator)",
            "Reed Emanuel Pal (Help Desk Supervisor)",
            "Kara Lott-Knott, Don Bothermy (Help Line Coordinators)",
            "Aretha Holley (Holiday Decoration Specialist)",
            "Don Weenau (Holiday Wardrobe Consultant)",
            "Mr. Ed (Horsepower Consultant)",
            "Doris Shutt (Hospitality Director)",
            "Al Ligori (In-house Literary Critic)",
            "Emile Endicott (In-law Hospitality Provider)",
            "Heidi Ductible (Insurance Agent)",
            "Perry Winkle (Interior Decorator)",
            "Tristan Schaut (Interpretive Dance Instructor)",
            "Mandalit Del Bar-Code (Inventory Manager)",
            "Aziz Nowarranty (Iraqi Sales Director)",
            "Hugh and Mia Donnagria (Italian Conflict Resolution Specialists)",
            "Donna Day Evvalurn (Italian Governess)",
            "C.V. Boutros Boutros Gali and Fidel Castrol (International Lubrication Experts)",
            "Lois Tess Gore (IQ Evaluator)",
            "Ian Bobby McGee (Janis Joplin Biographer)",
            "Benny Honda (Japanese Chef)",
            "Bertha Deblues (Jazz Music Coordinator)",
            "Jocelyn De Contents (Jeep Driver)",
            "Golda Myear (Jewelry Appraiser)",
            "Mehta Feingold (Jewelry Appraiser II)",
            "Stan Wellback (Jump Starting Expert)",
            "(Hatchback of Notre Dame) Quasi Automotive (Keeper of Bell Tower)",
            "Eustace Hammer (Laptop Repair Specialist)",
            "Gordon Diaz (Latin American Bullfighting Specialist)",
            "Noah Comprenday (Latin American Trade Representative)",
            "Harry Verderchi (Layoff Counselor)",
            "Oscar Lavista (Lay Off Counselor II)",
            "Eustace L. Emmons (Leader of The Former Peugeot Dealers of America Support Group)",
            "Author of Leo Tolstoy by Warren Peace (Leo Tolstoy biographer- Warren Peace)",
            "Isaiah Oldchap (Liaison to the British Isles)",
            "Roger Houston (Liaison to the Space Program)",
            "Bjorne Toulouse (Liaison Officer to Volvo & Renault)",
            "Sosumi Areti (Libel Defense Director in Tokyo)",
            "Shanda Lear (Lighting Expert)",
            "Ernest & Julio Hemingway (Literary Critics)",
            "Toto Payne Diaz (Little Dog of Payne-Diaz family)",
            "I.O. Silver (Loan Officer)",
            "Phil Mataleven (Local News Reporter)",
            "Ernest & Eustace Nailfile (Locksmith)",
            "Major Ashburn (Long Distance Cycling Enthusiast)",
            "Etienne Wheeler (Long-Distance Truck Driver)",
            "Darren D. Headlights (Long Range Economic Planner)",
            "Natasha D'Merchandise (Loss Prevention Associate)",
            "Lester Carey (Lost Luggage Tracker)",
            "Jason Rainbows (Lottery Ticket Coordinator)",
            "Tad Tolouse (Lug Nut Specialist)",
            "Hannah Mia Cannatunna (Luncheon Chef)",
            "Tony Diggs (Luxury Accomomdations Provider)",
            "Alfredo De-Daschund (Mailman)",
            "Francis Ford Cupholda (Manager of Automotive Accessories)",
            "Les Ismore (Manager of Car Talk Capital Depreciation Fund)",
            "Cy Burnett (Manager of Cartalk.Com)",
            "Wendy Pigsfly (Manager, Car Talk Listeners Rebate Program)",
            "Cameron Diaz (Manager, Donkey Based Video Equipment)",
            "Carmen Dating (Manager of Employee Refrigerator)",
            "Sheldon Deveigned (Manager of the Weekly Shrimp Buffet)",
            "Frieda Wales (Marine Biologist)",
            "Windsor Calm (Marine Forecaster)",
            "Marion Haste (Marriage Counselor)",
            "Anita Degroin (Martial Arts Trainer)",
            "Hannah Twomey (Mechanic's Assistant)",
            "Yehuda Guy (Missing Persons Investigator, from the Tel Aviv office)",
            "Mohammed Ahamana Hamana (Ralph Kramden Impersonator)",
            "Hugh Jim Bissell (Montana Traffic Law Director)",
            "Nora Lenderbee (Mortgage Loan Consultant)",
            "Stella Payne Diaz (Mother-in-Law Liaison)",
            "Boris Oxoff (Motivational Speaker)",
            "Carrie Desofa (Moving Van Driver)",
            "Desdamona Lisa (Museum Guide)",
            "Mel F. Lewis (Music Director)",
            "Donna E. Mobile (Musical Director)",
            "Jaswant Singh (Musical Theater Critic from the Bombay Office)",
            "Willie Mammoth (Natural History Curator)",
            "Ewell Flounder (New-Employee Training Program)",
            "Hugh Talkinamee (New York-based Dispute Settlement Coordinator)",
            "Roman Hunt (Nomadic Studies)",
            "Eaton Wright and Liven Good (Nutrition Consultants)",
            "Zbigniew Rigg (New Truck Reviewer)",
            "Don Kashane (Night Club Manager)",
            "Noah Merle Low (Wine Snob)",
            "Eliza Decouch (Official Football Widow)",
            "Nora Morse (Office Ice Cream Taster)",
            "Howie Vasive (Official Spokesperson)",
            "Lou Scannon (Official Spokesperson)",
            "Luke A. Boyd (Ornithologist in Training)",
            "Nicole Anne Dime (Our Chief Negotiator)",
            "Gene Hackman (Our DNA Researcher)",
            "Borden Drousy (Overnight Bus Driver)",
            "Emmanuel Recount (Overseer of Florida Voting Practices)",
            "Rick O'Shea (Parking Attendant)",
            "Ray Zador (Parking Garage Attendant)",
            "Kent Stirwell (Parking Lot Attendant)",
            "Willy Bolt (Parole Officer)",
            "Wayne Debach (Parts Inventory Manager)",
            "Edith Tu (Pastry Chef)",
            "Buck Le Vaugh (Pastry Chef II)",
            "Oren Jewison (Paternity Suit Researcher)",
            "Jay Walker (Pedestrian Advocate)",
            "Dot Comstock (Pension Fund Manager)",
            "Winston Paine (Periodontist)",
            "Oh Takashawa (Personal Hygiene Advisor from the Tokyo Office)",
            "Bud Tuggli (Personal Makeup Artist)",
            "Jim Shortz (Personal Trainer)",
            "Euripides Abs (Personal Trainer II)",
            "Arthur Katzenbach (Pet Shop Inventory Manager)",
            "Dave Reckoning (Petty Cash Auditor)",
            "Wanda Y. Datso (Philosopher)",
            "F. Stop Fitzgerald (Photographer)",
            "Eustace Kane (Physical Therapist)",
            "Estelle Hoyts (Physical Therapist)",
            "Laura Vernersha (Physics Graduate Student)",
            "Owen Too (Pitching Coach)",
            "Fay Slift (Plastic Surgeon)",
            "Kent Stan de Noyes (Podcast Reviewer)",
            "Robert Defrost (Poet Laureate)",
            "Althea Andrasia (Poker Coach)",
            "Mark Iavelli (Political Consultant)",
            "Paul C. Wonk (Political Consultant II)",
            "Shirley W. Money (Ponzi Scheme Operator)",
            "Boris Tadeff (PowerPoint Producer)",
            "Bea Esser (PR Director)",
            "Odessa Goodwyn (Practical Joke Evaluator)",
            "Dietrich Iznotulaff (Practical Joke Specialist)",
            "Denise Hurt (Prayer Coach)",
            "Giardia Brothers (Pre-show Caterers)",
            "Emerson Fittibaldie (he's also a client) (President, Car Talk Hair Club for Men)",
            "Ivana Trunk (President, Disgruntled Hatchback Owners Club)",
            "Don B. Zonozi (Press Secretary)",
            "Rick Kleiner (Producer's Office, Furnished by)",
            "Erin Spelling (Proof Reader)",
            "Euripedes Eumenedes (Proprietor of Car Talk's men clothing store)",
            "Melissa Forethought (Prosecuting Attorney)",
            "Norm De Plume (Pseudonym Consultant)",
            "Paul Murky of Murky Research (Public Opinion Pollster)",
            "Synchro de Mayo (Puerto Vallarta Transmission Specialist)",
            "Ida Klein (Public Appearances Coordinator)",
            "Otis S. Hard (Puzzler Tester)",
            "Andy Zoff (Race Team Driver)",
            "Euphrates Rapids (Rafting Guide)",
            "Hyman Oldcowhand (Ranch Foreman)",
            "Rita Menweip (Ratings Analysis Specialist)",
            "Zbigniew Payne Diaz (Recently Discovered Uncle from Warsaw)",
            "Sedona Tush (Receptionist)",
            "Levon Hold (Receptionist II)",
            "Frank Lee Scarlett (Regional Director, Atlanta)",
            "Kent B. Goode (Registered Mail Manager)",
            "Diana Comeback (Reincarnation Expert)",
            "Francis Ford Cupholda (Reluctant Film Editor)",
            "Ulysses Up (Rental Property Manager)",
            "Condoleeza B. Broken (Rental Property Manager)",
            "Bill M. Moore (Repair Cost Consultant)",
            "Carmine Now (Repo Agent)",
            "Trudy Door & Donna Hall (Restroom Attendants)",
            "Luisa Jolley Goodfellow (Retirement Party Planner)",
            "Benton Broke (Retractable Antenna Tester)",
            "Bruce Wade Hughes (Rock and Roll Historian)",
            "Chet Propeld (Rocket Scientist)",
            "Landon McKeester (Rollerblading Instructor)",
            "Vinnie V. Divici (Roman History Buff)",
            "Oliver D. Map (Route Planner)",
            "Vlad the Inhaler (Rumanian Emissions Tester)",
            "Anita Putin Newkarb (Russian-American Hesitation Specialist)",
            "Picov Andropov (Russian Chauffeur)",
            "Phillip Antopitov (Russian Gas Station Attendant)",
            "Igor Beaver (Russian Intern)",
            "Ivana Veekoff (Russian Vacation Specialist)",
            "Sarah Anne Getty (Safari Planner)",
            "Mort & Fay Tality (Safety Officers)",
            "Aziz Nowarranty (Sales Director)",
            "Norman Vincent Pealeout (Sales Motivation Coach)",
            "Candace B. Sirius (Satellite Radio Critic)",
            "Lawson D. Woods (Scout Leader)",
            "Howard E. Oysters (Seafood Provisioner)",
            "Mahmoud S. Bleak (Seasonal Adjustment Disorder Specialist)",
            "Mike Easter (Seat Cushion Tester)",
            "Rush Lumbar (Seating Consultant)",
            "Claudio Vernight (Second Shift Meteorologist)",
            "Les Aspirin (Secretary of Pain Relief)",
            "Made-A-Lane Allbright (Secretary of Halogen Headlamps)",
            "Fresh Prince (Secretary of Photographic Reproduction)",
            "Nina Cahones (Self Defense Instructor)",
            "Mia Culpa (Self Esteem Coach)",
            "Count De Monet (Senior Accountant from the Paris Office)",
            "Tonya Blinkeroff (Senior Citizen Driving Instructor)",
            "Seymour Robbiins (Senior Ornithologist)",
            "Holly Schmidt (Sensitive Language Advisor)",
            "Sven Diagram (Set Theorist from the Stockholm Office)",
            "Natasha Diaz (Sexual Harassment Counselor)",
            "Pat McCann (Sexual Harassment Intervention Counselor)",
            "Hans T. Josef (Sexual Harassment Trainer, Frankfurt Office)",
            "Luke Bizzy (Shop Foreman)",
            "Constance Ubervision (Shop Foreman II)",
            "Burt Toast (Short Order Cook)",
            "Seamus O'Dull (Show Reviewer)",
            "Chip Pentz (Sidewalk Clothing Vendor)",
            "Urethra Franklin (Singing Urologist)",
            "Betty Bayh (Sleep Clinic Operator)",
            "Procurer Caldwell Ahead (Sleepy LaBeef Ticket)",
            "Soren Dekeester (Snowboarding Instructor)",
            "Obie Quiet (Solicitor of New Ideas)",
            "Kerry Oki, Victor Yugo (Soloists)",
            "Senor Moment (Spanish Gerontologist)",
            "Tanya Lightov (Special Liaison to the California Energy Commission)",
            "Peter Aftermey (Speech Pathologist)",
            "Audrey Marx (Speechwriter)",
            "Miss Dolly Lama (Spiritual Counselor)",
            "Zeke and Ewell Find (Spiritual Counselors)",
            "Ivan Youlose (Sportsmanship Coach)",
            "Dewey Hafta (Staff Activities Coordinator)",
            "O. Howard Hertz (Staff Acupuncturist)",
            "Judy Cyde (Staff Advisor)",
            "Arianna Topyet (Staff Alpinist)",
            "Bernadette File (Staff Archivist)",
            "Four-Door Dostoevski (Staff Author)",
            "Buzz Wazleftov (Staff Barber)",
            "Les Offenbach (Staff Barber II)",
            "Maya Certz (Staff Bicycle Tester)",
            "Harry Mouval (Staff Bikini Waxer)",
            "Esther Iffick (Staff Brown Noser)",
            "Mahatma Coat (Staff Butler, from the Car Talk Bombay Division)",
            "Euripedes Ibrakauface (Staff Bouncer)",
            "Leslie Stahl (Staff Carburetor Expert)",
            "Angie O'Plasty (Staff Cardiologist)",
            "Frances N. Europe and Niles N. Africa (Staff Cartographers)",
            "Ken Opener (Staff Cat Feeder)",
            "Edith Ann Weepe (Staff Caterer)",
            "Theresa Crowd (Staff Chaperone)",
            "Neil Down (Staff Chaplain)",
            "Gordon Zola (Staff Cheese Expert)",
            "Drew Lee Weiner (Staff Child Seat Tester)",
            "Winston Paine (Staff Chiropractor)",
            "Gustav Muffler, Bela Cartok (Staff Composers)",
            "Al Dente, Sal Monella (Staff Cooks)",
            "Adeline Moore (Staff Copy Editor)",
            "Ivan Offalitch (Staff Dermatologist)",
            "Norma Lee Chowen (Staff Dietician)",
            "Les Stern (Staff Disciplinarian)",
            "Tara Neuwon (Staff Disciplinarian II)",
            "Juan Demerritt (Staff Disciplinarian III)",
            "Anton Chokeov (Staff Dramatist)",
            "Neera Nuff (Staff Fact Checker)",
            "Vera Similitude (Staff Forger)",
            "Dr. Louis Stuhls (Staff Gastroenterologist)",
            "Dr. Jean Poole (Staff Geneticist)",
            "Lorraine, Alsace (Staff Geographer)",
            "Spencer Cash (Staff Gigolo)",
            "Bud Inski (Staff Gossip Columnist.)",
            "Ariel Bummerman (Staff Grief Counselor)",
            "Manny Bumsfeldt (Staff Groper)",
            "Marsha Time (Staff Historian)",
            "Lois Rung (Staff Intern)",
            "Ivan Inkling (Staff Intuitionist)",
            "Joaquin Freezer (Staff Kitchen Designer)",
            "Heidi Silver (Staff Kleptomaniac)",
            "Alonzo Greene (Staff Landscaper)",
            "Oliver Twist (Staff Martini Mixer)",
            "Sue First (Staff Mediator)",
            "Collette Even (Staff Mediator II)",
            "Gail Storm (Staff Meteorologist)",
            "Claudio Vernight (Staff Meteorologist II)",
            "Luke Audavindo (Staff Meteorologist from New Delhi)",
            "Wayne Goaway (Staff Meteorologist from the Seattle Office)",
            "Donna Karen E. Moore (Staff Morale Coach)",
            "Barry L. Plotz and Sven Didigo (Staff Morticians)",
            "Diedre Oppings (Staff Naturalist)",
            "Arlene Menu (Staff Nutritionist)",
            "Studds Tercel (Staff Oral Historian)",
            "Marcia De Penguins (Staff Ornithologist, McMurdo Office)",
            "Denise Hoyt (Staff Orthopedist)",
            "Ray Zondette (Staff Philosopher)",
            "Moe Mentum (Staff Physicist)",
            "O. Luke Adair (Staff Prestidigitator)",
            "Anita Buttkiss (Staff Promotions Director)",
            "Les Moody (Staff Psychologist)",
            "Walter Windshield, Walter Crankcase (Staff Reporters)",
            "Avery Goodyear (Staff Sommelier)",
            "Frasier Tushov (Staff Snowplow Driver)",
            "Mike Romanage (Staff Supervisor)",
            "Condo Leaser Rice (Staff Temporary Housing Specialist)",
            "Willa Catheter (Staff Urologist)",
            "Pete Shedille (Staff Urologist II)",
            "Hans Auerbach (Standard Time Keeper)",
            "Lucinda Tung (State Secrets Keeper)",
            "Avery Haffenauer (Station Identification Coordinator)",
            "Marge Innovera (Statistician)",
            "Sloan Cranky (Studio Repair Technician)",
            "Gladys Overnow (Summer Intern)",
            "Bermuda Schwartz (Summer Wardrobe Coordinator)",
            "Les Brown (Sunscreen Provisioner)",
            "C.F.I. Care (Suppliers of Insurance to Dewey, Cheetham and Howe)",
            "Cal Abunga (Surf Reporter)",
            "C. Everett Koop DeVille (Surgeon General)",
            "Bjorn Liar (Swedish Attorney)",
            "Gunnar D. Daysr (Swedish Pessimist)",
            "C. Bigby Heinz (Swimwear Designer)",
            "Antonia Band-Era (Swing Dance Consultant)",
            "Les Digits (Table Saw Operator)",
            "Kurt Rhymer (Taciturn Poet)",
            "Euripedes Imenedes (Tailor)",
            "Lou Pole (Tax Consultant)",
            "Bernice Documents (Tax Preparer)",
            "Sasha Royal Payne Dias (Teenage Daughter)",
            "Lao Tse Parker (Teenage Valet)",
            "Opal Lease (Telephone Complaint Taker)",
            "Teresa Noboddihoum (Telephone Solicitation Response Specialist)",
            "Henri Lenting (Telephone Solicitor, Paris Office)",
            "Luke Underwood (Termite Inspector)",
            "Benjamin Not-Yet-You-Yahoo! (Timing Director)",
            "Cy Gazunt (Toastmaster)",
            "Emile Initself (Tom's Beard Cleaner)",
            "Edna Bagg (Tom's Personal Dating Coach)",
            "Stu Grody (Tommy's Ex House Cleaner)",
            "Roxanne Debris (Tommy's Front Yard Designer)",
            "Hugh Sherlock Familia (Tom's Memory Coach)",
            "Yvette de Pants (Tom's Official Co-Pilot)",
            "Annie Von Vildo (Tom's Other Dating Coach)",
            "Haseen Benisi (Tom's Personal Hygiene Coach)",
            "Robin D'Craydell (Tom's Personal Matchmaker)",
            "Terry Incognito (Tour Leader)",
            "Ralph Oliver (Town Car Rear Seat Passenger)",
            "Nina Clark and Alice Well (Town Criers)",
            "U.B. Crawlin (Traffic Reporter)",
            "Toulouse La Track (Train Derailment Specialist)",
            "Diana Boredom (Transcriber)",
            "Ben Her (Transgender Studies Expert)",
            "Rick Shaw (Transportation Coordinator)",
            "Lois Faire (Travel Agent)",
            "Vishnu Verhere (Travel Agent, Bombay Office)",
            "Althea Around (Travel Coordinator)",
            "Ariel Payne Diaz (Two Year Old)",
            "I.C. London (Undergarment Inspector)",
            "Candace Waite (Urgent Response Coordinator)",
            "Alexis Itznot (Used Car Salesman)",
            "Meg Meehan Hoffa (Used Car Salesperson)",
            "Cosmo Lean (Vehicle Preservation Specialist)",
            "Schlomo Replay (Videographer, Tel Aviv Office)",
            "Dale Neverknow (Visually Impaired Parking Lot Attendant)",
            "Luke Howard Fitzhugh (Wardrobe Advisor)",
            "Harley Fitzhugh (Wardrobe Advisor II)",
            "Joaquin Closet (Wardrobe Assistant)",
            "Natalie Attired (Wardrobe Consultant)",
            "Candace B. Rittenoff (Warrantee Claim Adjudicator)",
            "Deepak Tumuch (Weekend Excursion Planner)",
            "Hugh Otto Dewitt (Weight Loss Coach)",
            "Harriet Knight (Werewolf Studies Specialist)",
            "Curt and Rod (Window Dressers)",
            "Ike and Zeke Leerly (Windshield Wiper Replacement Team)",
            "Eileen Windy (Windsurfing Instructor)",
            "Hassen Ben Sober (Wine Taster from the Abu Dhabi Office)",
            "Miss Inga Tooth (Women's Hockey Team)",
            "Leo Del Lahey Hy (Yodeling Instructor from Hawaii"
        };

        #endregion

        public RandomData()
        {
            // Without this, sometimes two tests will get the same seed value.
            System.Threading.Thread.Sleep(1);
        }

        public DateTime Date(int minYear, int maxYear)
        {
            return Date(new DateTime(minYear, 1, 1), new DateTime(maxYear - 1, 12, 31, 23, 59, 59));
        }

        public DateTime Date(DateTime min, DateTime max)
        {
            return new DateTime(Long(min.Ticks, max.Ticks));
        }

        public long Long(long min, long max)
        {
            return min + Convert.ToInt64((max - min) * _random.NextDouble());
        }

        public string Ipsum(int minWords, int maxWords)
        {
            return Ipsum(_random.Next(minWords, maxWords));
        }

        public string Word()
        {
            return _words[_random.Next(_words.Length - 1)];
        }

        public string NameAndTitle()
        {
            return _names[_random.Next(_names.Length - 1)];
        }

        public string Ipsum(int numWords)
        {
            var result = new StringBuilder("lorem");
            for (var i = 1; i < 5; i++)
            {
                if (i >= numWords)
                    return result.ToString();
                result.Append(" ").Append(_words[i - 1]);
            }
            for (var i = 6; i < numWords; i++)
                result.Append(" ").Append(Word());
            return result.ToString();
        }

        public int Int(int min, int max)
        {
            return _random.Next(min, max);
        }

        public int Int(int max)
        {
            return _random.Next(max);
        }

        public string Format(string format)
        {
            var sb = new StringBuilder();
            foreach (var ch in format)
            {
                switch (ch)
                {
                    case '0':
                        sb.Append(_random.Next(9).ToString(CultureInfo.InvariantCulture));
                        break;
                    case 'U':
                        sb.Append(Convert.ToChar(_random.Next(65, 90)));
                        break;
                    case 'l':
                        sb.Append(Convert.ToChar(_random.Next(97, 122)));
                        break;
                    default:
                        sb.Append(ch);
                        break;
                }
            }
            return sb.ToString();
        }

        public T Item<T>(List<T> list)
        {
            return list[_random.Next(list.Count - 1)];
        }

        public TK Value<T, TK>(Dictionary<T, TK> dictionary)
        {
            var keys = dictionary.Keys.ToList();
            return dictionary[Item(keys)];
        }

        private string GenString(int size, int minChr, int maxChr)
        {
            var sb = new StringBuilder();
            for (int i = 0; i < size; i++)
            {
                sb.Append(Convert.ToChar(_random.Next(minChr, maxChr)));
            }
            return sb.ToString();
        }

        public string NumberString(int size)
        {
            return GenString(size, 48, 57);
        }

        public string Upper(int size)
        {
            return GenString(size, 65, 90);
        }

        public string Lower(int size)
        {
            return GenString(size, 97, 122);
        }

        public string Phone()
        {
            return Format("555-000-0000");
        }
    }
}
